### ISSUE TITLE
Expand to encompass all opensource at UCLA

### ISSUE THREAD

**Issue by BryanPan342** [uclaacm/opensource#7]
**[Use Case]**
Create a website that highlights opensource at UCLA and acts as a centralized location for the going-on of tech across UCLA. 

The current structure of the repository lends itself to be shared across multiple organizations. Wouldn't it be phenomenal to have any organization at UCLA showcase their opensource projects? It would be a great place for new students, older students, alumni, recruiters, and professors to see what exactly UCLA is up to.

**[Proposed Solution]**

Utilize a PR (opt-in) mechanism for organizations to display their projects on the site.

*Process*
- PR to add a new config to the repository
   - Specify route (website.com/[slug])
   - Add tags and organization information (name, github, etc)
   - Choose a type of data retrieval (yml, contentful, json, strapi, netlify cms, google sheets)
- Aggregate your orgnanization's data in your chosen content model 
- Customize: create custom templates, css frameworks, whatever to showcase your organization and club

Example configuration:

```yml
slug: cl
org_name: Creative Labs
website: https://creativelabsucla.com/
github: UCLA-Creative-Labs

data: contentful
contentful_delivery_token: xxxXXXxxx         // These can be public because they are simply delivery
contentful_space_id: xxx
```

We would need to do some nifty development to inject custom css / javascript into a dynamic route, but it seems like a good challenge.

I also would be down to do some sort of liquid markdown!

```
---
slug: cl
org_name: Creative Labs
website: https://creativelabsucla.com/
github: UCLA-Creative-Labs

data: contentful
contentful_delivery_token: xxxXXXxxx         // These can be public because they are simply delivery
contentful_space_id: xxx
---

# Code

[insert code block here]

# Styling

[insert code block here]

```
